# Use Python base image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy application files
COPY app/ /app/
COPY requirements/test.txt /app/requirements.txt
COPY requirements/run.txt /app/run.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the application port
EXPOSE 5000
EXPOSE 5678

# Run the application
CMD ["python", "app.py"]