version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "5678:5678"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - DEBUG_ENABLED=1
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./app/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        API_TOKEN: ${API_TOKEN}
    ports:
      - "3000:3000"
      - "80:80"
    env_file:
      - .env
    depends_on:
      - app

volumes:
  db_data: