version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-debug
    ports:
      - "5000:5000"
      - "5678:5678"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - DEBUG_ENABLED=1
    env_file:
      - .env

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./app/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev  # Uses Node.js for development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/fe
      - /fe/node_modules  # Preserve node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable hot reloading
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - client

volumes:
  db_data: