version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./app/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

volumes:
  db_data: