version: '3.8'

services:
  app:
    image: teragoatz/rk10:latest
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./app/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile  # Uses Apache for production
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data: