version: '3.8'

services:
  app:
    image: teragoatz/rk10-app:latest
    environment:
      - POSTGRES_HOST=db
      - RK10_CLIENT_HOST=client
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./app/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  client:
    image: teragoatz/rk10-client:latest
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data: