# Use Python base image
FROM python:3.12-alpine

# Set working directory
WORKDIR /app

# Copy application files
COPY . /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements/test.txt

# Expose the application port
EXPOSE 5000
EXPOSE 5678

# Run the application
CMD ["python", "app.py"]